import type { Account, Category, Settings } from '@/types/entities'

const now = () => new Date().toISOString()

/**
 * Category colors are an implementation decision — §2/§5 don't define a
 * per-category palette (the 5 named accents are reserved for
 * income/expense/warning/info/liability meaning). To keep that rule intact,
 * three categories that ARE one of those concepts reuse the matching accent
 * (EMI/Loans → liability purple, Salary → income emerald, Transfers → info
 * blue); every other category gets its own distinct hue purely for visual
 * scanning, none of which collide with the 5 semantic accents.
 */
export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: 'cat-food',
    name: 'Food',
    icon: 'UtensilsCrossed',
    color: '#EA580C',
    parentCategory: null,
    displayOrder: 0,
    isDefault: true,
    isArchived: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'cat-fuel',
    name: 'Fuel',
    icon: 'Fuel',
    color: '#0891B2',
    parentCategory: null,
    displayOrder: 1,
    isDefault: true,
    isArchived: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'cat-shopping',
    name: 'Shopping',
    icon: 'ShoppingBag',
    color: '#DB2777',
    parentCategory: null,
    displayOrder: 2,
    isDefault: true,
    isArchived: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'cat-utilities',
    name: 'Utilities',
    icon: 'Zap',
    color: '#65A30D',
    parentCategory: null,
    displayOrder: 3,
    isDefault: true,
    isArchived: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'cat-food-delivery',
    name: 'Food Delivery',
    icon: 'Bike',
    color: '#C026D3',
    parentCategory: null,
    displayOrder: 4,
    isDefault: true,
    isArchived: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'cat-health',
    name: 'Health',
    icon: 'HeartPulse',
    color: '#DC2626',
    parentCategory: null,
    displayOrder: 5,
    isDefault: true,
    isArchived: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'cat-entertainment',
    name: 'Entertainment',
    icon: 'Film',
    color: '#4F46E5',
    parentCategory: null,
    displayOrder: 6,
    isDefault: true,
    isArchived: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'cat-emi-loans',
    name: 'EMI/Loans',
    icon: 'Landmark',
    color: '#8B5CF6',
    parentCategory: null,
    displayOrder: 7,
    isDefault: true,
    isArchived: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'cat-salary',
    name: 'Salary',
    icon: 'Wallet',
    color: '#10B981',
    parentCategory: null,
    displayOrder: 8,
    isDefault: true,
    isArchived: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'cat-transfers',
    name: 'Transfers',
    icon: 'ArrowLeftRight',
    color: '#3B82F6',
    parentCategory: null,
    displayOrder: 9,
    isDefault: true,
    isArchived: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'cat-other',
    name: 'Other',
    icon: 'MoreHorizontal',
    color: '#78716C',
    parentCategory: null,
    displayOrder: 10,
    isDefault: true,
    isArchived: false,
    createdAt: now(),
    updatedAt: now(),
  },
]

/** §6 default accounts: Cash, Bank Account, Credit Card, UPI Wallet,
 * Emergency Fund. All start at a zero balance; the user sets an opening
 * balance during onboarding or their first edit. */
export const DEFAULT_ACCOUNTS: Account[] = [
  {
    id: 'acc-cash',
    name: 'Cash',
    type: 'cash',
    icon: 'Banknote',
    color: '#16A34A',
    openingBalance: 0,
    currentBalance: 0,
    isDefault: true,
    isArchived: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'acc-bank',
    name: 'Bank Account',
    type: 'bank',
    icon: 'Landmark',
    color: '#2563EB',
    openingBalance: 0,
    currentBalance: 0,
    isDefault: true,
    isArchived: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'acc-credit-card',
    name: 'Credit Card',
    type: 'creditCard',
    icon: 'CreditCard',
    color: '#9333EA',
    openingBalance: 0,
    currentBalance: 0,
    isDefault: true,
    isArchived: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'acc-upi',
    name: 'UPI Wallet',
    type: 'upiWallet',
    icon: 'Smartphone',
    color: '#0D9488',
    openingBalance: 0,
    currentBalance: 0,
    isDefault: true,
    isArchived: false,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'acc-emergency-fund',
    name: 'Emergency Fund',
    type: 'emergencyFund',
    icon: 'ShieldCheck',
    color: '#CA8A04',
    openingBalance: 0,
    currentBalance: 0,
    isDefault: true,
    isArchived: false,
    createdAt: now(),
    updatedAt: now(),
  },
]

/** §5 Settings Entity defaults. `onboardingCompleted` isn't in the spec's
 * field list — flagged as an added field; see build notes. */
export const DEFAULT_SETTINGS: Settings = {
  id: 'active',
  theme: 'system',
  currency: 'INR',
  currencyDisplay: 'lakh-crore',
  dateFormat: 'DD/MM/YYYY',
  language: 'en',
  defaultView: 'dashboard',
  budgetMonthStart: 1,
  backupFrequency: 'off',
  firstDayOfWeek: 0,
  animationEnabled: true,
  hapticFeedback: false,
  compactMode: false,
  appLockEnabled: false,
  appLockPinHash: null,
  developerMode: false,
  onboardingCompleted: false,
  sampleDataRequested: false,
}
